#!/bin/bash

export SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

if [ ! -f $SCRIPT_DIR/node/node ]; then
  echo "Nodejs missing, please run mvn install"
elif [ ! -f $SCRIPT_DIR/node_modules/.bin/bower ]; then
  echo "Bower missing, please run mvn install"
else
  export PATH=$SCRIPT_DIR/node_modules/.bin:$SCRIPT_DIR/node:$PATH
fi
