package io.nflow.rest.v1.msg;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import io.nflow.engine.model.ModelObject;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Response for submit new workflow instance")
@SuppressFBWarnings(value = "URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD", justification = "jackson reads dto fields")
public class CreateWorkflowInstanceResponse extends ModelObject {

  @Schema(description = "Identifier of the new workflow instance", required = true, format = "int64")
  public long id;

  @Schema(description = "Workflow definition type", required = true)
  public String type;

  @Schema(description = "Main business key or identifier for the workflow instance")
  public String businessKey;

  @Schema(description = "Unique external identifier within workflow type. Generated by nFlow if not given.", required = true,
      minLength = 1, maxLength = 64)
  public String externalId;

}
