package io.nflow.rest.v1.msg;

import javax.validation.constraints.Size;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import io.nflow.engine.model.ModelObject;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Response for submit new workflow instance")
@SuppressFBWarnings(value="URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD", justification="jackson reads dto fields")
public class CreateWorkflowInstanceResponse extends ModelObject {

  @Schema(description = "Idenfier of the new workflow instance", required = true)
  public long id;

  @Schema(description = "Workflow definition type", required = true)
  public String type;

  @Schema(description = "Main business key or identifier for the workflow instance (e.g. credit application identifier)")
  public String businessKey;

  @Size(max=64)
  @Schema(description = "Unique external identifier under workflow type. Generated by nflow if not given.")
  public String externalId;

}
