package io.nflow.rest.v1.msg;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import io.nflow.engine.model.ModelObject;
import io.swagger.v3.oas.annotations.media.Schema;

import static io.swagger.v3.oas.annotations.media.Schema.RequiredMode.REQUIRED;

@Schema(description = "Response for submit new workflow instance")
@SuppressFBWarnings(value = "URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD", justification = "jackson reads dto fields")
public class CreateWorkflowInstanceResponse extends ModelObject {

  @Schema(description = "Identifier of the new workflow instance", requiredMode = REQUIRED, format = "int64")
  public long id;

  @Schema(description = "Workflow definition type", requiredMode = REQUIRED)
  public String type;

  @Schema(description = "Executor Group")
  public String executorGroup;

  @Schema(description = "Main business key or identifier for the workflow instance")
  public String businessKey;

  @Schema(description = "Unique external identifier within workflow type. Generated by nFlow if not given.", requiredMode = REQUIRED,
      minLength = 1, maxLength = 64)
  public String externalId;

}
