package com.nitorcreations.nflow.rest.v1.msg;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.Size;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;

@ApiModel(description = "Response for submit new workflow instance")
@SuppressFBWarnings(value="URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD", justification="jackson reads dto fields")
public class CreateWorkflowInstanceResponse {

  @ApiModelProperty(value = "Idenfier of the new workflow instance", required=true)
  public int id;

  @ApiModelProperty(value = "Workflow definition identifier (e.g. withdrawLoan", required=true)
  public String type;

  @ApiModelProperty("Main business key or identifier for the started workflow instance (e.g. credit application identifier)")
  public String businessKey;

  @Size(max=64)
  @ApiModelProperty("Unique external identifier under workflow type. Generated by nflow if not given.")
  public String externalId;

}
