package com.nitorcreations.nflow.rest.v1.msg;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.joda.time.DateTime;

import com.fasterxml.jackson.databind.JsonNode;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;

@ApiModel(description =
  "Request for submit new workflow instance. Note that if externalId is given, " +
  "type and externalId pair must be unique hence enabling retry-safety.")
@SuppressFBWarnings(value="URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD", justification="jackson reads dto fields")
public class CreateWorkflowInstanceRequest {

  @NotNull
  @Size(max=30)
  @ApiModelProperty(value = "Workflow definition identifier", required=true)
  public String type;

  @Size(max=64)
  @ApiModelProperty("Main business key or identifier for the started workflow instance")
  public String businessKey;

  @Size(max=64)
  @ApiModelProperty("Start state identifier if other than default initial state set in workflow definition")
  public String startState;

  @Size(max=64)
  @ApiModelProperty("Unique external identifier under workflow type. Generated by nflow if not given.")
  public String externalId;

  @ApiModelProperty("JSON document that contains business information")
  public JsonNode requestData;

  @ApiModelProperty("Start time for workflow execution, if missing 'now'")
  public DateTime activationTime;

}
