package com.nitorcreations.nflow.rest.v1.msg;

import java.util.List;
import java.util.Map;

import org.joda.time.DateTime;

import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;

@ApiModel(value = "Basic information of workflow instance")
@SuppressFBWarnings(value="URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD", justification="jackson reads dto fields")
public class ListWorkflowInstanceResponse {

  @ApiModelProperty(value = "Identifier of the new workflow instance", required=true)
  public int id;

  @ApiModelProperty(value = "Workflow instance status: 'created', 'executing', 'inProgress', 'finished', 'manual', 'stopped'", required = true)
  public String status;

  @ApiModelProperty(value = "Workflow definition identifier", required=true)
  public String type;

  @ApiModelProperty(value = "Parent workflow instance id for child workflows", required=false)
  public Integer parentWorkflowId;

  @ApiModelProperty(value = "Parent workflow instance action id for child workflows", required=false)
  public Integer parentActionId;

  @ApiModelProperty(value = "Main business key or identifier for the started workflow instance", required=false)
  public String businessKey;

  @ApiModelProperty(value = "Unique external identifier under workflow type. Generated by nflow if not given.", required=true)
  public String externalId;

  @ApiModelProperty(value = "State of the workflow instance", required=true)
  public String state;

  @ApiModelProperty(value = "Text of describing the reason for state (free text)", required=false)
  public String stateText;

  @ApiModelProperty(value = "Next activation time for workflow instance processing", required=false)
  public DateTime nextActivation;

  @ApiModelProperty(value = "State variables for current state.", required=false)
  public Map<String, Object> stateVariables;

  @ApiModelProperty(value = "Number of times current state has been retried.", required=true)
  public int retries;

  @ApiModelProperty(value = "State change attempts. One instance for each processing attempt.", required=false)
  public List<Action> actions;

  @ApiModelProperty(value = "Workflow instance creation timestamp", required=true)
  public DateTime created;

  @ApiModelProperty(value = "Workflow instance latest modification timestamp", required=true)
  public DateTime modified;

  @ApiModelProperty(value = "Time when workflow processing stared (start time for first action)", required=false)
  public DateTime started;

  @ApiModelProperty(value = "Child workflow instance IDs created by this instance, grouped by instance action ID", required = false)
  public Map<Integer, List<Integer>> childWorkflows;
}
