name: PR Build
on:
  push
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Run the Maven test phase
        run: mvn --no-transfer-progress --color=always clean install spotbugs:spotbugs
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
      - name: Spotbugs
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'
  matrix:
    needs: build
    strategy:
      matrix:
        java: [ '11', '17' ]
        db: [ 'h2', 'mariadb', 'postgresql', 'mysql', 'sqlserver' ]
        exclude:
          # java 11 + h2 was already tested in basic build
          - java: 11
            db: h2
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: nflow.db.${{ matrix.db }}
      DB_VERSION: ${{ matrix.java == 11 && 'old' || 'latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup DB
        run: ./scripts/setup-db-${{ matrix.db }}.sh
      - name: Create frontend package
        run: mvn --no-transfer-progress --color=always -pl nflow-explorer install
      - name: Compile code
        run: mvn --no-transfer-progress --color=always -P ${{ matrix.db }} -Dskip.npm -Dskip.bower -Dskip.grunt -am -pl nflow-tests test-compile
      - name: Run the integration tests
        run: mvn --no-transfer-progress --color=always -P ${{ matrix.db }} -Dskip.npm -Dskip.bower -Dskip.grunt -pl nflow-tests test
