name: Build and test
on:
  push
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Run the Maven build, tests, JavaDocs and SpotBugs
        run: mvn --no-transfer-progress --color=always -Dmaven.source.skip=true clean test
      - name: Publish JUnit Test Report
        uses: scacap/action-surefire-report@v1
        if: always()
  check-javadoc-and-spotbugs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Run the Maven build, tests, JavaDocs and SpotBugs
        run: mvn --no-transfer-progress --color=always -Dmaven.source.skip=true -Dskip.npm -Dskip.bower -Dskip.grunt compile javadoc:javadoc spotbugs:spotbugs
      - name: Publish SpotBugs Report
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'
  integration-tests:
    needs: build
    strategy:
      matrix:
        java: [ '11', '17' ]
        db: [ 'h2', 'mariadb', 'postgresql', 'mysql', 'sqlserver' ]
        exclude:
          # java 11 + h2 was already tested in basic build
          - java: 11
            db: h2
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: nflow.db.${{ matrix.db }}
      DB_VERSION: ${{ matrix.java == 11 && 'old' || 'latest' }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up database
        run: ./scripts/setup-db-${{ matrix.db }}.sh
      - name: Run the integration tests
        run: mvn --offline --color=always -P ${{ matrix.db }} -Dskip.npm -Dskip.bower -Dskip.grunt -pl nflow-tests test
