name: PR Build
on:
  push:
    branches-ignore:
    - 'master'
concurrency: 
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        java: [ '11' ]
        db: [ 'h2', 'mariadb' ]
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: nflow.db.${{ matrix.db }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup DB
        run: ./travis/setup-db-${{ matrix.db }}.sh ${{ matrix.java }}
      - name: Create frontend package
        run: mvn -X -B -pl nflow-explorer install
      - name: Run the Maven test phase
        run: mvn -X -B -P ${{ matrix.db }} test
